spring:
  config:
    activate:
      on-profile:
        - dev
  mvc:
    view:
      prefix: /views/
      suffix: .html
  datasource:
    url: jdbc:mysql://123.60.166.170:3306/personnel?&serverTimezone=Asia/Shanghai&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: personnel
    password: 123456789@a
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认5分钟
      idle-timeout: 300000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 30
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 15000
