spring:
  profiles:
    active: dev
  #  修改上传文件大小
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


server:
  port: 80
  tomcat:
    max-connections: 0
    max-http-form-post-size: 0
    threads:
      max: 0
      min-spare: 30
